# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-12 11:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('one', '0004_usermodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cart_goods_num', models.IntegerField(default=1)),
                ('cart_belong', models.BooleanField(default=False)),
                ('cart_check', models.BooleanField(default=True)),
                ('cart_goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='one.MarketGoods')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_time', models.DateTimeField(auto_now=True)),
                ('order_status', models.IntegerField(default=0)),
                ('order_user', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='one.UserModel')),
            ],
        ),
        migrations.AddField(
            model_name='cart',
            name='cart_order',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='one.Order'),
        ),
        migrations.AddField(
            model_name='cart',
            name='cart_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='one.UserModel'),
        ),
    ]
